CREATE TABLE IF NOT EXISTS currencies (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Code VARCHAR(10) UNIQUE NOT NULL,
    Full_Name VARCHAR(100) NOT NULL,
    Sign VARCHAR(10) NOT NULL
);

CREATE TABLE IF NOT EXISTS exchange_rates (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Base_Currency_Id INTEGER,
    Target_Currency_Id INTEGER,
    Rate DECIMAL(6, 3) NOT NULL,
    FOREIGN KEY (Base_Currency_Id) REFERENCES Currencies(ID),
    FOREIGN KEY (Target_Currency_Id) REFERENCES Currencies(ID),
    UNIQUE (Base_Currency_Id, Target_Currency_Id)
);

-- drop table currencies cascade;
-- drop table exchange_rates;